apiVersion: v1
description: Fredboat is a Discord bot that plays music.
name: fredboat
version: 1.0.0
appVersion: 1.0.0
icon: https://fredboat.com/static/media/logo.79b4fd81.svg
home: https://fredboat.com/
sources:
  - https://github.com/Frederikam/FredBoat
keywords:
  - discord
  - bot
