apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fredboat.fullname" . }}-sentinel
  labels:
    app: {{ include "fredboat.labels.app" . }}
    component: sentinel
    chart: {{ include "fredboat.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fredboat.labels.app" . }}
      component: sentinel
  template:
    metadata:
      labels:
        app: {{ include "fredboat.labels.app" . }}
        component: sentinel
    spec:
      {{- if .Values.fredboat.sentinel.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.fredboat.sentinel.image.pullSecret }}
      {{- end }}
      containers:
      - name: fredboat-sentinel
        resources:
          requests:
            memory: 250Mi
          limits:
            memory: 350Mi
        image: {{ .Values.fredboat.sentinel.image.repository }}:{{ .Values.fredboat.sentinel.image.tag }}
        imagePullPolicy: {{ .Values.fredboat.sentinel.image.pullPolicy}}
        env:
        - name: SPRING_RABBITMQ_ADDRESSES
          value: amqp://guest:guest@fredboat-rabbitmq
        ports:
        - containerPort: 2333
        volumeMounts:
        - name: secret-volume
          mountPath: /opt/sentinel/common.yml
          subPath: fredboat-common.yaml
      volumes:
        - name: secret-volume
          secret:
            secretName: {{ include "fredboat.fullname" . }}-configs
