apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fredboat.fullname" . }}-lavalink-networkpolicy
spec:
  podSelector:
    matchLabels:
      app: {{ include "fredboat.labels.app" . }}
      component: lavalink
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Fredboat bot talks to Lavalink.
  - from:
    - podSelector:
        matchLabels:
          app: {{ include "fredboat.labels.app" . }}
          component: bot
    ports:
    - protocol: TCP
      port: 2333
  egress:
  # Lavalink talks to the Internet.
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.0.0.0/8
          - 192.168.0.0/16
          - 172.16.0.0/20
  # Explicitly allow DNS.
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
