apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "fredboat.fullname" . }}-configs
stringData:
  lavalink.yaml: |
    server:
      port: 2333
      address: 0.0.0.0
    spring:
      main:
        banner-mode: log
    lavalink:
      server:
        password: "{{ .Values.fredboat.lavalink.password }}"
        sources:
          youtube: true
          bandcamp: true
          soundcloud: true
          twitch: true
          vimeo: true
          mixer: true
          http: true
          local: false
        bufferDurationMs: 400
        youtubePlaylistLoadLimit: 600
        gc-warnings: true

    metrics:
      prometheus:
        enabled: false
        endpoint: /metrics

    sentry:
      dsn: "{{ Values.fredboat.lavalink.sentryDsn }}"

    logging:
      file:
        max-history: 30
        max-size: 1GB
      path: ./logs/

      level:
        root: INFO
        lavalink: INFO
  fredboat-common.yaml: |-
    discordToken: "{{ .Values.fredboat.apikeys.discord }}"
  fredboat-quarterdeck.yaml: |-
    security:
      admins:
      - name: "{{ .Values.fredboat.quarterdeck.username }}"
        pass: "{{ .Values.fredboat.quarterdeck.password }}"

    whitelist:
      userIds: []

    spring:
      main:
        banner-mode: log
      output:
        ansi:
          enabled: detect

    server:
      port: 4269

    sentry:
      dsn: "{{ Values.fredboat.quarterdeck.sentryDsn }}"

    database:
      main:
        jdbcUrl: "jdbc:postgresql://fredboat-postgres:5432/fredboat?user=fredboat"

      cache:
        jdbcUrl: "jdbc:postgresql://fredboat-postgres:5432/fredboat?user=fredboat"

    logging:
      file:
        max-history: 30
        max-size: 1GB
      path: ./logs/

      level:
        root: INFO
        fredboat: DEBUG
        com.fredboat: DEBUG

    docs:
      open: false
      host: ""
      basePath: ""
  fredboat-bot.yaml: |-
    config:
      development: false
      prefix: '{{BotPrefix}}'
      botAdmins: []
      botOwners: []
      autoBlacklist: true
      game: "{{NowPlaying}}"
      continuePlayback: false
      shardCount: 1

    server:
      port: 1356

    spring:
      main:
        web-application-type: none
      output:
        ansi:
          enabled: detect

    audio-sources:
      enableYouTube: true
      enableSoundCloud: true
      enableBandCamp: true
      enableTwitch: true
      enableVimeo: true
      enableMixer: true
      enableSpotify: true
      enableLocal: false
      enableHttp: true

    backend:
      quarterdeck:
        host: "http://fredboat-quarterdeck:4269/"
        user: "{{ .Values.fredboat.quarterdeck.username }}"
        pass: "{{ .Values.fredboat.quarterdeck.password }}"

    credentials:
      googleApiKeys:
        - "{{ .Values.fredboat.apikeys.youtube }}"
      #discordBotToken: ""
      imgurClientId: ""
      spotifyId: ""
      spotifySecret: ""
      openWeatherKey: ""
      sentryDsn: ""

    event-logger:
      eventLogWebhook: ""
      eventLogInterval: 1
      guildStatsWebhook: ""
      guildStatsInterval: 60

    lavalink:
      nodes:
        - name : "local"
          host : "ws://fredboat-lavalink:2333"
          pass : "{{ .Values.fredboat.lavalink.password }}"

    logging:
      file:
        max-history: 30
        max-size: 1GB
      path: ./logs/

      level:
        root: INFO
        fredboat: DEBUG
        com.fredboat: DEBUG
        net.dv8tion: DEBUG
