apiVersion: v1
kind: Service
metadata:
  name: {{ include "fredboat.fullname" . }}-rabbitmq
  labels:
    app: {{ include "fredboat.labels.app" . }}
    component: rabbitmq
    chart: {{ include "fredboat.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: broker
    port: 5672
  - name: web-ui
    port: 15672
  clusterIP: None
  selector:
    app: {{ include "fredboat.labels.app" . }}
    component: rabbitmq
