apiVersion: v1
kind: Service
metadata:
  name: {{ include "fredboat.fullname" . }}-postgres
  labels:
    app: {{ include "fredboat.labels.app" . }}
    component: postgres
    chart: {{ include "fredboat.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: {{ include "fredboat.labels.app" . }}
    component: postgres
